from app.database_interface.exceptions.__base import BaseDatabaseException


class Conflict(BaseDatabaseException):
    pass
